name: 'Solana Anchor Build'
author: 'MRGN Labs'
description: 'Build a Solana program with Anchor'
branding:
  icon: anchor
  color: red
inputs:
  args:
    description: 'anchor build arguments'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'projectserum/build:v0.24.2'
  entrypoint: shell-exec
  args: 
    - 'anchor build ${{ inputs.args }}'
